name: Deploy Frontend
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'frontend'
          slot-name: 'your-slot-name' # Optional
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './client'
